version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: book-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: book_manager
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: sajjadhossain0/book_cicd:main-48f2d65
    container_name: book-app
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
